debian/kaffeine.xpm /usr/share/pixmaps
debian/presubj /usr/share/bug/kaffeine/
usr/bin/kaffeine
usr/bin/kaffeine-xbu
usr/share/applications/kde4/kaffeine.desktop
usr/share/icons/oxygen/*/actions/audio-radio-encrypted.png
usr/share/icons/oxygen/*/actions/video-television-encrypted.png
usr/share/kde4/apps/solid/actions/kaffeine_play_audiocd.desktop
usr/share/kde4/apps/solid/actions/kaffeine_play_dvd.desktop
usr/share/kde4/apps/solid/actions/kaffeine_play_videocd.desktop
usr/share/locale/*/LC_MESSAGES/kaffeine.mo
